#服务名称
server:
  port: 8300

#连接配置
spring:
  application:
    name: config_server_jdbc
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        default-label: master
        jdbc:
          sql: SELECT akey , avalue FROM config_env where APPLICATION=? and APROFILE=? and LABEL=?

  #mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.222.111:3306/student
    username: root
    password: 123456

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

